export const fontMap = {
  inter: "'Inter', sans-serif",
  roboto: "'Roboto', sans-serif",
  opensans: "'Open Sans', sans-serif",
  lato: "'Lato', sans-serif",
  montserrat: "'Montserrat', sans-serif",
  georgia: "'Georgia', serif",
  playfair: "'Playfair Display', serif",
  merriweather: "'Merriweather', serif",
  garamond: "'EB Garamond', serif",
  times: "'Times New Roman', serif",
};

export const websiteTypes = [
  { value: 'business', label: 'Business/Corporate' },
  { value: 'portfolio', label: 'Portfolio/Creative' },
  // { value: 'ecommerce', label: 'E-commerce' },
  // { value: 'blog', label: 'Blog' },
  { value: 'landing', label: 'Landing Page' },
  { value: 'educational', label: 'Educational' },
  { value: 'nonprofit', label: 'Non-profit' },
  { value: 'personal', label: 'Personal' },
  { value: 'resume', label: 'Resume/CV' },
  { value: 'event', label: 'Event' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'photography', label: 'Photography' },
  { value: 'app', label: 'App Landing' },
  { value: 'coming_soon', label: 'Coming Soon' },
  { value: 'other', label: 'Other' },
];

export const fontOptions = [
  { value: 'Inter', label: 'Inter', category: 'Sans Serif' },
  { value: 'Roboto', label: 'Roboto', category: 'Sans Serif' },
  { value: 'Open Sans', label: 'Open Sans', category: 'Sans Serif' },
  { value: 'Lato', label: 'Lato', category: 'Sans Serif' },
  { value: 'Montserrat', label: 'Montserrat', category: 'Sans Serif' },
  { value: 'Poppins', label: 'Poppins', category: 'Sans Serif' },
  { value: 'Georgia', label: 'Georgia', category: 'Serif' },
  { value: 'Merriweather', label: 'Merriweather', category: 'Serif' },
  { value: 'Playfair Display', label: 'Playfair Display', category: 'Serif' },
  { value: 'Courier New', label: 'Courier New', category: 'Monospace' },
  { value: 'Source Code Pro', label: 'Source Code Pro', category: 'Monospace' },
];

export const primaryFonts = [
  {
    label: 'Sans Serif',
    options: fontOptions.filter((font) => font.category === 'Sans Serif'),
  },
  {
    label: 'Serif',
    options: fontOptions.filter((font) => font.category === 'Serif'),
  },
  {
    label: 'Monospace',
    options: fontOptions.filter((font) => font.category === 'Monospace'),
  },
];

export const secondaryFonts = [
  {
    label: 'Sans Serif',
    options: fontOptions.filter((font) => font.category === 'Sans Serif'),
  },
  {
    label: 'Serif',
    options: fontOptions.filter((font) => font.category === 'Serif'),
  },
  {
    label: 'Monospace',
    options: fontOptions.filter((font) => font.category === 'Monospace'),
  },
];

export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, North',
  'Korea, South',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const plans = [
  {
    title: 'Free',
    description: 'Ideal for individuals who need quick access to basic features.',
    monthlyPrice: 'Free',
    monthlyPlanId: '',
    yearlyPlanId: 'plan_FREE123_YEAR',
    yearlyPrice: 'Free',
    getIn: [
      { description: '1 website with 2 webpages', rightIcon: true, bold: true },
      { description: 'Access to stock images', rightIcon: true },
      { description: 'Image editing - 2', rightIcon: true },
      { description: 'Conversational AI content update - 5', rightIcon: true },
      { description: 'Website modifications & updates - 10', rightIcon: true },
      { description: 'Mega Menu without advanced dropdown access', rightIcon: true },
      { description: 'AI workspace - 2MB storage', rightIcon: true },
      { description: 'Monthly visitor Tracking - 500 visitors', rightIcon: true },
      { description: 'Whatsapp Chat integration', rightIcon: true },
      { description: 'Email support', rightIcon: true },
      { description: 'Help manual (docs+ Videos)', rightIcon: true },
    ],
    features: {
      totalSites: 1,
      websitePages: 2,
      responsiveWebDesign: true,
      megaMenu: true,
      stockImageAccess: true,
      imageEditing: 2,
      conversationalAiContentUpdate: 5,
      websiteModificationsUpdates: 10,
      addYourOwnDomain: false,
      officeIqAiChatbot: false,
      whatsappBotIntegration: true,
      builtInSeo: false,
      websiteAnalyticsDashboard: false,
      aiWorkspace: true,
      workspaceStorageLimit: '2 MB',
      monthlyVisitorLimit: 500,
      mobileApp: true,
      hostingDuration: false,
      supportPlan: true,
      supportChannels: 'EmailSupport',
      whiteLabeledBranding: false,
      crmIntegration: false,
      helpCenter: 'Doc+Video',
      humanizedContentCreation: false,
      officeIqChatIntegration: false,
    },
  },
  {
    title: 'Basic',
    description: 'Great for personal sites with essential features.',
    minDiscountYearly: 10,
    maxDiscountYearly: 50,
    monthlyPrice: 975,
    monthlyPlanId: 'plan_Qln15cDvYReyBR',
    yearlyPlanId: 'plan_QlniLE5A8An1yp', // prod- plan_QgKOEPJ8rcG6Mp
    yearlyPrice: 8999,
    planIds: [
      'plan_Qlpb88I3pXILlA', // 1 year
      'plan_Qlpb8yoD5oEJzO', // 2 year
      'plan_Qlpb9iyG0ubmRv', // 3 year
      'plan_QlpbAVsDcEnMkG', // 4 year
      'plan_QlpbBATEvkKvLb', // 5 year
      'plan_QlpbBpTUs4UtsN', // 6 year
      'plan_QlpbCX4yG427hJ', // 7 year
      'plan_QlpbDD6IYvkRnC', // 8 year
      'plan_QlpbDxI3Aheacn', // 9 year
      'plan_QlpbEbe2UGU9Gf', // 10 year
    ],
    getIn: [
      { description: '1 website with 5 webpages', rightIcon: true, bold: true },
      { description: 'Access to stock images', rightIcon: true },
      { description: 'Mega menu with advanced dropdown access', rightIcon: true },
      { description: 'Image editing -', rightIcon: true, key: 'imageEditing' },
      {
        description: 'Conversational AI content update -',
        key: 'conversationalAiContentUpdate',
        rightIcon: true,
      },
      {
        description: 'Website modifications & updates -',
        key: 'websiteModificationsUpdates',
        rightIcon: true,
      },
      { description: 'Add your own domain', rightIcon: true },
      { description: 'Domain hosting', key: 'hostingDuration', rightIcon: true },
      { description: 'Built-in SEO and basic website analytics dashboard', rightIcon: true },
      {
        description: 'AI workspace storage -',
        key: 'workspaceStorageLimit',
        rightIcon: true,
      },
      {
        description: 'Monthly visitor Tracking -',
        key: 'monthlyVisitorLimit',
        rightIcon: true,
      },
      { description: 'White-labeled branding', rightIcon: true },
      { description: 'CRM integration (Paid Add-On)', rightIcon: true },
      { description: 'Whatsapp Chat integration', rightIcon: true },
      { description: 'Email support', rightIcon: true },
      { description: 'Help manual (docs+ Videos)', rightIcon: true },
    ],
    features: {
      totalSites: 1,
      websitePages: 5,
      imageEditing: 12,
      conversationalAiContentUpdate: 50,
      websiteModificationsUpdates: 50,
      workspaceStorageLimit: '500 MB',
      monthlyVisitorLimit: 2000,
      hostingDuration: '1 Years',
      responsiveWebDesign: true,
      megaMenu: true,
      stockImageAccess: true,
      addYourOwnDomain: true,
      officeIqAiChatbot: false,
      whatsappBotIntegration: true,
      builtInSeo: true,
      websiteAnalyticsDashboard: 'basic',
      aiWorkspace: true,
      mobileApp: true,
      supportPlan: true,
      supportChannels: 'EmailSupport',
      whiteLabeledBranding: true,
      crmIntegration: true,
      helpCenter: 'Doc+Video',
      humanizedContentCreation: false,
      officeIqChatIntegration: false,
    },
  },
  {
    title: 'Pro',
    description: 'For professionals who need enhanced AI features and tools.',
    minDiscountYearly: 12,
    maxDiscountYearly: 52,
    monthlyPrice: 1408,
    monthlyPlanId: 'plan_Qln1Rb9eusDwf6',
    yearlyPlanId: 'plan_Qln5bq8GwcZZTM', // prod- plan_QgKOhStqf6QjmK
    yearlyPrice: 12999,
    planIds: [
      'plan_QlpwOV6BlTu9jp', // year1
      'plan_QlpwPE1fg3grPr', // year2
      'plan_QlpwPzjuByxKuT', // year3
      'plan_QlpwQeAooR5mp7', // year4
      'plan_QlpwRIXgjE74UY', // year5
      'plan_QlpwS0edILGvjQ', // year6
      'plan_QlpwSfED9o9Pje', // year7
      'plan_QlpwTLAPSVW3KM', // year8
      'plan_QlpwU9vYUSLN18', // year9
      'plan_QlpwUuJUAwttPs', // year10
    ],
    getIn: [
      { description: '1 website with 10 webpages', rightIcon: true, bold: true },
      { description: 'Access to stock images', rightIcon: true },
      { description: 'Mega menu and Footer Menu with advanced dropdown access', rightIcon: true },
      { description: 'Unlimited image editing', rightIcon: true },
      {
        description: 'Conversational AI content update -',
        rightIcon: true,
        key: 'conversationalAiContentUpdate',
      },
      {
        description: 'Website modifications & updates -',
        rightIcon: true,
        key: 'websiteModificationsUpdates',
      },
      { description: 'Add your own domain', rightIcon: true },
      {
        description: 'Domain hosting',
        rightIcon: true,
        key: 'hostingDuration',
      },
      { description: 'OfficeIQ AI-powered chatbot', rightIcon: true },
      { description: 'Built-in SEO and advanced website analytics dashboard', rightIcon: true },
      {
        description: 'AI workspace storage -',
        rightIcon: true,
        key: 'workspaceStorageLimit',
      },
      {
        description: 'Monthly visitor Tracking -',
        rightIcon: true,
        key: 'monthlyVisitorLimit',
      },
      { description: 'White-labeled branding', rightIcon: true },
      { description: 'CRM integration (Paid Add-On)', rightIcon: true },
      { description: 'Whatsapp Chat integration with auto replies', rightIcon: true },
      { description: 'Email + AI bot support', rightIcon: true },
      { description: 'Help manual (docs+ Videos)', rightIcon: true },
    ],
    features: {
      totalSites: 1,
      websitePages: 10,
      responsiveWebDesign: true,
      megaMenu: true,
      stockImageAccess: true,
      imageEditing: true,
      conversationalAiContentUpdate: 250,
      websiteModificationsUpdates: 250,
      addYourOwnDomain: true,
      officeIqAiChatbot: true,
      whatsappBotIntegration: 'autoReplies',
      builtInSeo: true,
      websiteAnalyticsDashboard: 'advance',
      aiWorkspace: true,
      workspaceStorageLimit: '1 GB',
      monthlyVisitorLimit: 10000,
      mobileApp: true,
      hostingDuration: '1 Years',
      supportPlan: true,
      supportChannels: 'Email + AI Bot Support',
      whiteLabeledBranding: true,
      crmIntegration: true,
      helpCenter: 'Doc+Video',
      humanizedContentCreation: false,
      officeIqChatIntegration: true,
    },
  },
  {
    title: 'Advance',
    description: 'Perfect for small businesses that want power and scale.',
    minDiscountYearly: 15,
    maxDiscountYearly: 55,
    monthlyPrice: 1625,
    monthlyPlanId: 'plan_Qln1oXSvbMhqi8',
    yearlyPlanId: 'plan_Qln6B4NFOYlI1A', // prod- plan_QgKOzDAJMnV2yD
    yearlyPrice: 14999,
    planIds: [
      'plan_QlqK4F6IBiy5ri', // 1 year
      'plan_QlqK4xQ5dvIuJw', // 2 year
      'plan_QlqK5lDws7Mjho', // 3 year
      'plan_QlqK6STYCIRNXA', // 4 year
      'plan_QlqK7AT8yNnA64', // 5 year
      'plan_QlqK7s3dbnHhjb', // 6 year
      'plan_QlqK8bxs0WFibw', // 7 year
      'plan_QlqK9GryFkTSRH', // 8 year
      'plan_QlqK9vALqUBvDz', // 9 year
      'plan_QlqKAaNlWPCMuZ', // 10 year
    ],
    getIn: [
      { description: '3 websites with 15 webpages', rightIcon: true, bold: true },
      { description: 'Access to stock images', rightIcon: true },
      { description: 'Mega menu and Footer Menu with advanced dropdown access', rightIcon: true },
      { description: 'Unlimited image editing', rightIcon: true },
      {
        description: 'Conversational AI content update -',
        rightIcon: true,
        key: 'conversationalAiContentUpdate',
      },
      {
        description: 'Website modifications & updates -',
        rightIcon: true,
        key: 'websiteModificationsUpdates',
      },
      { description: 'Add your own domain', rightIcon: true },
      {
        description: 'Domain hosting',
        rightIcon: true,
        key: 'hostingDuration',
      },
      { description: 'OfficeIQ AI-powered chatbot', rightIcon: true },
      { description: 'Built-in SEO and advanced website analytics dashboard', rightIcon: true },
      {
        description: 'AI workspace storage -',
        rightIcon: true,
        key: 'workspaceStorageLimit',
      },
      {
        description: 'Monthly visitor Tracking -',
        key: 'monthlyVisitorLimit',
        rightIcon: true,
      },
      { description: 'White-labeled branding', rightIcon: true },
      { description: 'CRM integration (Paid Add-On)', rightIcon: true },
      { description: 'Whatsapp Bot integration with auto replies', rightIcon: true },
      { description: 'Email + Phone support', rightIcon: true },
      { description: 'Help manual (docs+ Videos)', rightIcon: true },
      { description: 'AI Humanizer Copilot', rightIcon: true },
      { description: 'OfficeIQ Conversational AI Platform', rightIcon: true },
    ],
    features: {
      totalSites: 3,
      websitePages: 15,
      responsiveWebDesign: true,
      megaMenu: true,
      stockImageAccess: true,
      imageEditing: true,
      conversationalAiContentUpdate: 500,
      websiteModificationsUpdates: 500,
      addYourOwnDomain: true,
      officeIqAiChatbot: 'chatbotPlusLeadCapture',
      whatsappBotIntegration: 'autoReplies',
      builtInSeo: true,
      websiteAnalyticsDashboard: 'advance',
      aiWorkspace: true,
      workspaceStorageLimit: '1 GB',
      monthlyVisitorLimit: 50000,
      mobileApp: true,
      hostingDuration: '6 Years',
      supportPlan: true,
      supportChannels: 'Email + Phone Support',
      whiteLabeledBranding: true,
      crmIntegration: true,
      helpCenter: 'Doc+Video',
      humanizedContentCreation: true,
      officeIqChatIntegration: true,
    },
  },
  {
    title: 'Enterprise',
    description: 'Built for enterprises with custom needs and scale.',
    monthlyPrice: 'Contact Us',
    monthlyPlanId: '',
    yearlyPlanId: 'plan_ENT123456789',
    yearlyPrice: 'Contact Us',
    getIn: [
      { description: 'Access to stock images', rightIcon: true, bold: true },
      { description: 'Mega menu and Footer Menu with advanced dropdown access', rightIcon: true },
      { description: 'Image editing', rightIcon: true },
      { description: 'Conversational AI content updates', rightIcon: true },
      { description: 'Unlimited website modifications & updates', rightIcon: true },
      { description: 'Add your own domain', rightIcon: true },
      { description: 'Domain hosting 10 years', rightIcon: true },
      { description: 'OfficeIQ AI-powered chatbot with lead capture', rightIcon: true },
      { description: 'Built-in SEO and advanced website analytics dashboard', rightIcon: true },
      { description: 'AI workspace', rightIcon: true },
      { description: 'Monthly visitor Tracking', rightIcon: true },
      { description: 'White-labeled branding', rightIcon: true },
      { description: 'CRM integration (Paid Add-On)', rightIcon: true },
      { description: 'Whatsapp Bot integration with auto replies', rightIcon: true },
      { description: 'Dedicated priority email + phone support', rightIcon: true },
      { description: 'Help manual (docs+ Videos)', rightIcon: true },
      { description: 'AI Humanizer Copilot', rightIcon: true },
      { description: 'OfficeIQ Conversational AI Platform', rightIcon: true },
    ],
    features: {
      totalSites: '',
      websitePages: '',
      responsiveWebDesign: true,
      megaMenu: true,
      stockImageAccess: true,
      imageEditing: true,
      conversationalAiContentUpdate: '',
      websiteModificationsUpdates: '',
      addYourOwnDomain: true,
      officeIqAiChatbot: 'chatbotPlusLeadCapture',
      whatsappBotIntegration: 'aiChatbotAdvanced',
      builtInSeo: true,
      websiteAnalyticsDashboard: 'advance',
      aiWorkspace: true,
      workspaceStorageLimit: '',
      monthlyVisitorLimit: '',
      mobileApp: true,
      hostingDuration: '10 Years',
      supportPlan: true,
      supportChannels: 'Dedicated Priority Support',
      whiteLabeledBranding: true,
      crmIntegration: true,
      helpCenter: 'Doc+Video',
      humanizedContentCreation: true,
      officeIqChatIntegration: true,
    },
  },
];

export const internationalPlans = [
  {
    title: 'Free',
    description: 'Ideal for individuals who need quick access to basic features.',
    yearlyPlanId: 'plan_FREE123_YEAR',
    yearlyPrice: 'Free',
    monthlyPrice: 'Free',
    monthlyPlanId: '',
    getIn: [
      {
        bold: true,
        description: '1 website with 2 webpages',
        rightIcon: true,
      },
      {
        description: 'Access to stock images',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Image editing - 2',
      },
      {
        description: 'Conversational AI content update - 5',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Website modifications & updates - 10',
      },
      {
        rightIcon: true,
        description: 'Mega Menu without advanced dropdown access',
      },
      {
        rightIcon: true,
        description: 'AI workspace - 2MB storage',
      },
      {
        rightIcon: true,
        description: 'Monthly visitor Tracking - 500 visitors',
      },
      {
        rightIcon: true,
        description: 'Whatsapp Chat integration',
      },
      {
        rightIcon: true,
        description: 'Email support',
      },
      {
        description: 'Help manual (docs+ Videos)',
        rightIcon: true,
      },
    ],
    features: {
      helpCenter: 'Doc+Video',
      officeIqChatIntegration: false,
      websitePages: 2,
      workspaceStorageLimit: '2 MB',
      megaMenu: true,
      crmIntegration: false,
      humanizedContentCreation: false,
      whiteLabeledBranding: false,
      addYourOwnDomain: false,
      aiWorkspace: true,
      mobileApp: true,
      supportPlan: true,
      imageEditing: 2,
      responsiveWebDesign: true,
      monthlyVisitorLimit: 500,
      totalSites: 1,
      conversationalAiContentUpdate: 5,
      websiteAnalyticsDashboard: false,
      supportChannels: 'EmailSupport',
      whatsappBotIntegration: true,
      websiteModificationsUpdates: 10,
      builtInSeo: false,
      stockImageAccess: true,
      hostingDuration: false,
      officeIqAiChatbot: false,
    },
  },
  {
    title: 'Basic',
    description: 'Great for personal sites with essential features.',
    monthlyPrice: 24,
    yearlyPrice: 288,
    monthlyPlanId: 'plan_QoXhG6Sre7Uefb',
    yearlyPlanId: 'plan_QoX9HNNfBapV6H',
    minDiscountYearly: 15,
    maxDiscountYearly: 50,
    planIds: [
      'plan_QoX9HNNfBapV6H',
      'plan_QoX9I5dqIBAuXR',
      'plan_QoX9Io42hn3CAc',
      'plan_QoX9JWeSC7q9V4',
      'plan_QoX9KDzz09jCaX',
      'plan_QoX9L0UZBjlrrP',
      'plan_QoX9LmU1L9JxtL',
      'plan_QoX9Mdg2QRhKB6',
      'plan_QoX9NJbdfOQFDc',
      'plan_QoX9OJR0w1ui5g',
    ],
    getIn: [
      {
        bold: true,
        description: '1 website with 5 webpages',
        rightIcon: true,
      },
      {
        description: 'Access to stock images',
        rightIcon: true,
      },
      {
        description: 'Mega menu with advanced dropdown access',
        rightIcon: true,
      },
      {
        rightIcon: true,
        key: 'imageEditing',
        description: 'Image editing -',
      },
      {
        rightIcon: true,
        key: 'conversationalAiContentUpdate',
        description: 'Conversational AI content update -',
      },
      {
        rightIcon: true,
        key: 'websiteModificationsUpdates',
        description: 'Website modifications & updates -',
      },
      {
        rightIcon: true,
        description: 'Add your own domain',
      },
      {
        key: 'hostingDuration',
        description: 'Domain hosting',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Built-in SEO and basic website analytics dashboard',
      },
      {
        description: 'AI workspace storage -',
        rightIcon: true,
        key: 'workspaceStorageLimit',
      },
      {
        description: 'Monthly visitor Tracking -',
        key: 'monthlyVisitorLimit',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'White-labeled branding',
      },
      {
        description: 'CRM integration (Paid Add-On)',
        rightIcon: true,
      },
      {
        description: 'Whatsapp Chat integration',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Email support',
      },
      {
        description: 'Help manual (docs+ Videos)',
        rightIcon: true,
      },
    ],
    features: {
      addYourOwnDomain: true,
      humanizedContentCreation: false,
      workspaceStorageLimit: '500 MB',
      officeIqAiChatbot: false,
      builtInSeo: true,
      officeIqChatIntegration: false,
      hostingDuration: '1 Years',
      mobileApp: true,
      conversationalAiContentUpdate: 50,
      websiteModificationsUpdates: 50,
      websitePages: 5,
      responsiveWebDesign: true,
      stockImageAccess: true,
      websiteAnalyticsDashboard: 'basic',
      monthlyVisitorLimit: 2000,
      aiWorkspace: true,
      imageEditing: 12,
      crmIntegration: true,
      supportChannels: 'EmailSupport',
      supportPlan: true,
      megaMenu: true,
      whatsappBotIntegration: true,
      whiteLabeledBranding: true,
      totalSites: 1,
      helpCenter: 'Doc+Video',
    },
  },
  {
    title: 'Pro',
    description: 'For professionals who need enhanced AI features and tools.',
    yearlyPrice: 588,
    monthlyPrice: 49,
    maxDiscountYearly: 50,
    minDiscountYearly: 15,
    yearlyPlanId: 'plan_QoXRNrqjyZZ5q2',
    monthlyPlanId: 'plan_QoXhb6qjIymTkv',
    planIds: [
      'plan_QoXRNrqjyZZ5q2',
      'plan_QoXROWjFD4usJs',
      'plan_QoXRPCvxjFfcNA',
      'plan_QoXRPsHoy742YV',
      'plan_QoXRQV3OywiyJf',
      'plan_QoXRR8TXQ7J9fo',
      'plan_QoXRRmKUhH0nED',
      'plan_QoXRSSWDQgLN5X',
      'plan_QoXRT9wBnnHu8e',
      'plan_QoXRTt5BoF16wm',
    ],
    getIn: [
      {
        rightIcon: true,
        description: '1 website with 10 webpages',
        bold: true,
      },
      {
        description: 'Access to stock images',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Mega menu and Footer Menu with advanced dropdown access',
      },
      {
        description: 'Unlimited image editing',
        rightIcon: true,
      },
      {
        key: 'conversationalAiContentUpdate',
        rightIcon: true,
        description: 'Conversational AI content update -',
      },
      {
        key: 'websiteModificationsUpdates',
        description: 'Website modifications & updates -',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Add your own domain',
      },
      {
        key: 'hostingDuration',
        description: 'Domain hosting',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'OfficeIQ AI-powered chatbot',
      },
      {
        rightIcon: true,
        description: 'Built-in SEO and advanced website analytics dashboard',
      },
      {
        rightIcon: true,
        description: 'AI workspace storage -',
        key: 'workspaceStorageLimit',
      },
      {
        rightIcon: true,
        description: 'Monthly visitor Tracking -',
        key: 'monthlyVisitorLimit',
      },
      {
        description: 'White-labeled branding',
        rightIcon: true,
      },
      {
        description: 'CRM integration (Paid Add-On)',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Whatsapp Chat integration with auto replies',
      },
      {
        rightIcon: true,
        description: 'Email + AI bot support',
      },
      {
        description: 'Help manual (docs+ Videos)',
        rightIcon: true,
      },
    ],
    features: {
      websitePages: 10,
      supportPlan: true,
      stockImageAccess: true,
      conversationalAiContentUpdate: 250,
      imageEditing: true,
      whiteLabeledBranding: true,
      websiteAnalyticsDashboard: 'advance',
      supportChannels: 'Email + AI Bot Support',
      megaMenu: true,
      builtInSeo: true,
      humanizedContentCreation: false,
      officeIqAiChatbot: true,
      mobileApp: true,
      responsiveWebDesign: true,
      aiWorkspace: true,
      monthlyVisitorLimit: 10000,
      hostingDuration: '1 Years',
      whatsappBotIntegration: 'autoReplies',
      crmIntegration: true,
      helpCenter: 'Doc+Video',
      totalSites: 1,
      officeIqChatIntegration: true,
      workspaceStorageLimit: '1 GB',
      websiteModificationsUpdates: 250,
      addYourOwnDomain: true,
    },
  },
  {
    title: 'Advance',
    description: 'Perfect for small businesses that want power and scale.',
    monthlyPrice: 89,
    yearlyPrice: 1068,
    minDiscountYearly: 15,
    maxDiscountYearly: 50,
    monthlyPlanId: 'plan_QoXhrxvKpb5GND',
    yearlyPlanId: 'plan_QoXRiCFjmVTAOx',
    planIds: [
      'plan_QoXRiCFjmVTAOx',
      'plan_QoXRisNybPwu3e',
      'plan_QoXRjXxG6Vk0Rk',
      'plan_QoXRkFE26RZA31',
      'plan_QoXRkwhefWdizd',
      'plan_QoXRla4mlaE8ph',
      'plan_QoXRmGfeLBlMoe',
      'plan_QoXRmwdFDlacrz',
      'plan_QoXRnYXcqPfzQD',
      'plan_QoXRoCxvawRy3t',
    ],
    getIn: [
      {
        bold: true,
        description: '3 websites with 15 webpages',
        rightIcon: true,
      },
      {
        description: 'Access to stock images',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Mega menu and Footer Menu with advanced dropdown access',
      },
      {
        description: 'Unlimited image editing',
        rightIcon: true,
      },
      {
        rightIcon: true,
        key: 'conversationalAiContentUpdate',
        description: 'Conversational AI content update -',
      },
      {
        description: 'Website modifications & updates -',
        rightIcon: true,
        key: 'websiteModificationsUpdates',
      },
      {
        description: 'Add your own domain',
        rightIcon: true,
      },
      {
        rightIcon: true,
        key: 'hostingDuration',
        description: 'Domain hosting',
      },
      {
        rightIcon: true,
        description: 'OfficeIQ AI-powered chatbot',
      },
      {
        description: 'Built-in SEO and advanced website analytics dashboard',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'AI workspace storage -',
        key: 'workspaceStorageLimit',
      },
      {
        description: 'Monthly visitor Tracking -',
        rightIcon: true,
        key: 'monthlyVisitorLimit',
      },
      {
        description: 'White-labeled branding',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'CRM integration (Paid Add-On)',
      },
      {
        description: 'Whatsapp Bot integration with auto replies',
        rightIcon: true,
      },
      {
        description: 'Email + Phone support',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Help manual (docs+ Videos)',
      },
      {
        description: 'AI Humanizer Copilot',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'OfficeIQ Conversational AI Platform',
      },
    ],
    features: {
      supportPlan: true,
      supportChannels: 'Email + Phone Support',
      imageEditing: true,
      aiWorkspace: true,
      monthlyVisitorLimit: 50000,
      builtInSeo: true,
      megaMenu: true,
      addYourOwnDomain: true,
      humanizedContentCreation: true,
      officeIqAiChatbot: 'chatbotPlusLeadCapture',
      websitePages: 15,
      stockImageAccess: true,
      conversationalAiContentUpdate: 500,
      responsiveWebDesign: true,
      mobileApp: true,
      totalSites: 3,
      websiteModificationsUpdates: 500,
      hostingDuration: '1 Years',
      whatsappBotIntegration: 'autoReplies',
      crmIntegration: true,
      helpCenter: 'Doc+Video',
      whiteLabeledBranding: true,
      officeIqChatIntegration: true,
      websiteAnalyticsDashboard: 'advance',
      workspaceStorageLimit: '5 GB',
    },
  },
  {
    title: 'Enterprise',
    description: 'Built for enterprises with custom needs and scale.',
    yearlyPrice: 'Contact Us',
    monthlyPrice: 'Contact Us',
    yearlyPlanId: 'plan_ENT123456789',
    monthlyPlanId: '',
    getIn: [
      {
        bold: true,
        description: 'Access to stock images',
        rightIcon: true,
      },
      {
        description: 'Mega menu and Footer Menu with advanced dropdown access',
        rightIcon: true,
      },
      {
        description: 'Image editing',
        rightIcon: true,
      },
      {
        description: 'Conversational AI content updates',
        rightIcon: true,
      },
      {
        description: 'Unlimited website modifications & updates',
        rightIcon: true,
      },
      {
        description: 'Add your own domain',
        rightIcon: true,
      },
      {
        description: 'Domain hosting 10 years',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'OfficeIQ AI-powered chatbot with lead capture',
      },
      {
        description: 'Built-in SEO and advanced website analytics dashboard',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'AI workspace',
      },
      {
        rightIcon: true,
        description: 'Monthly visitor Tracking',
      },
      {
        rightIcon: true,
        description: 'White-labeled branding',
      },
      {
        rightIcon: true,
        description: 'CRM integration (Paid Add-On)',
      },
      {
        description: 'Whatsapp Bot integration with auto replies',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'Dedicated priority email + phone support',
      },
      {
        description: 'Help manual (docs+ Videos)',
        rightIcon: true,
      },
      {
        rightIcon: true,
        description: 'AI Humanizer Copilot',
      },
      {
        rightIcon: true,
        description: 'OfficeIQ Conversational AI Platform',
      },
    ],
    features: {
      whiteLabeledBranding: true,
      workspaceStorageLimit: '',
      totalSites: '',
      imageEditing: true,
      supportPlan: true,
      supportChannels: 'Dedicated Priority Support',
      crmIntegration: true,
      whatsappBotIntegration: 'aiChatbotAdvanced',
      responsiveWebDesign: true,
      humanizedContentCreation: true,
      builtInSeo: true,
      officeIqAiChatbot: 'chatbotPlusLeadCapture',
      conversationalAiContentUpdate: '',
      websiteAnalyticsDashboard: 'advance',
      megaMenu: true,
      mobileApp: true,
      addYourOwnDomain: true,
      websitePages: '',
      websiteModificationsUpdates: '',
      stockImageAccess: true,
      officeIqChatIntegration: true,
      monthlyVisitorLimit: '',
      aiWorkspace: true,
      hostingDuration: '10 Years',
      helpCenter: 'Doc+Video',
    },
  },
];
